[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Force redeployment on every push
[build.processing]
  skip_processing = false

# ==========================================
# SCHEDULED FUNCTIONS (CRON Jobs)
# ==========================================

# Fonction 1 : Rappels d'inactivité (tous les jours à 10h Paris = 8h UTC)
[functions."send-reminders"]
  schedule = "0 8 * * *"

# Fonction 2 : Récapitulatif mensuel (1er du mois à 9h Paris = 7h UTC)
[functions."monthly-report"]
  schedule = "0 7 1 * *"

# ==========================================
# Redirects et Headers
# ==========================================

# Headers de sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "frame-src 'self' https://player.vimeo.com"

# Cache des assets statiques
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"


